services:
  app:
    image: cocktailserver-app
    build: .
    volumes:
      - ./:/usr/src//app
    ports:
      - "5050:5050"
    depends_on:
      - db
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: CocktailAppDB
    volumes:
      - mysqldata:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
    ports:
      - "5000:5000"
  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"  
        
volumes:
  mysqldata: {}