"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const admin_controller_1 = require("../controllers/admin.controller");
const router = (0, express_1.Router)();
router.get("/getAllUsers", admin_controller_1.getAllUsers);
router.get("/getUnvalidCocktails", admin_controller_1.getUnvalidCocktails);
router.post("/approveCocktail", admin_controller_1.approveCocktail);
router.post("/rejectCocktail", admin_controller_1.rejectCocktail);
router.post("/deleteUser", admin_controller_1.deleteUser);
exports.default = router;
